package net.phoenix.core.common.machine;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.GTValues;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.data.chemical.ChemicalHelper;
import com.gregtechceu.gtceu.api.data.tag.TagPrefix;
import com.gregtechceu.gtceu.api.machine.IMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.MetaMachine;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.recipe.OverclockingLogic;
import com.gregtechceu.gtceu.api.registry.registrate.MachineBuilder;
import com.gregtechceu.gtceu.common.data.*;
import com.gregtechceu.gtceu.common.data.machines.GTResearchMachines;
import com.gregtechceu.gtceu.common.machine.multiblock.part.CleaningMaintenanceHatchPartMachine;
import com.gregtechceu.gtceu.data.lang.LangHandler;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.TextColor;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;
import net.phoenix.core.client.renderer.machine.multiblock.CosmicDynamicRenderHelpers;
import net.phoenix.core.common.block.PhoenixBlocks;
import net.phoenix.core.common.data.PhoenixRecipeTypes;
import net.phoenix.core.common.data.materials.PhoenixMaterials;
import net.phoenix.core.common.data.recipe.PhoenixRecipeModifiers;
import net.phoenix.core.common.machine.multiblock.BlazingCleanroom;
import net.phoenix.core.common.machine.multiblock.CreativeEnergyMultiMachine;
import net.phoenix.core.common.machine.multiblock.electric.research.PhoenixHPCAMachine;
import net.phoenix.core.configs.PhoenixConfigs;
import net.phoenix.core.phoenixcore;

import java.util.Locale;
import java.util.function.BiFunction;

import static com.gregtechceu.gtceu.api.GTValues.*;
import static com.gregtechceu.gtceu.api.pattern.Predicates.*;
import static com.gregtechceu.gtceu.common.data.GTBlocks.*;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;
import static net.phoenix.core.common.registry.PhoenixRegistration.REGISTRATE;
import static net.phoenix.core.configs.PhoenixConfigs.INSTANCE;

@SuppressWarnings("all")
public class PhoenixMachines {

    public static MultiblockMachineDefinition DANCE = null;
    public static MachineDefinition BLAZING_CLEANING_MAINTENANCE_HATCH = null;
    public static MachineDefinition HIGH_YEILD_PHOTON_EMISSION_REGULATER = null;
    static {
        REGISTRATE.creativeModeTab(() -> phoenixcore.PHOENIX_CREATIVE_TAB);
    }

    static {
        if (PhoenixConfigs.INSTANCE.features.blazingHatchEnabled) {
            BLAZING_CLEANING_MAINTENANCE_HATCH = REGISTRATE
                    .machine("blazing_cleaning_maintenance_hatch",
                            holder -> new CleaningMaintenanceHatchPartMachine(holder,
                                    BlazingCleanroom.BLAZING_CLEANROOM))
                    .langValue("Blazing Cleaning Maintenance Hatch")
                    .rotationState(RotationState.ALL)
                    .abilities(PartAbility.MAINTENANCE)
                    .tooltips(Component.translatable("gtceu.part_sharing.disabled"),
                            Component.translatable("gtceu.machine.maintenance_hatch_cleanroom_auto.tooltip.0"),
                            Component.translatable("gtceu.machine.maintenance_hatch_cleanroom_auto.tooltip.1"))
                    .tooltipBuilder((stack, tooltips) -> tooltips.add(Component.literal("  ").append(Component
                            .translatable(BlazingCleanroom.BLAZING_CLEANROOM.getTranslationKey())
                            .withStyle(ChatFormatting.RED))))
                    .tier(UHV)

                    .overlayTieredHullModel(
                            phoenixcore.id("block/machine/part/overlay_maintenance_blazing_cleaning"))
                    // Tier can always be changed later
                    .register();
        }
    }

    public static MachineDefinition[] registerTieredMachines(String name,
                                                             BiFunction<IMachineBlockEntity, Integer, MetaMachine> factory,
                                                             BiFunction<Integer, MachineBuilder<MachineDefinition>, MachineDefinition> builder,
                                                             int... tiers) {
        MachineDefinition[] definitions = new MachineDefinition[GTValues.TIER_COUNT];
        for (int tier : tiers) {
            var register = REGISTRATE
                    .machine(GTValues.VN[tier].toLowerCase(Locale.ROOT) + "_" + name,
                            holder -> factory.apply(holder, tier))
                    .tier(tier);
            definitions[tier] = builder.apply(tier, register);
        }
        return definitions;
    }

    static {
        if (PhoenixConfigs.INSTANCE.features.creativeEnergyEnabled) {
            DANCE = REGISTRATE
                    .multiblock("phoenix_infuser", CreativeEnergyMultiMachine::new)
                    .langValue("&Phoenix Infuser")
                    .rotationState(RotationState.NON_Y_AXIS)
                    .recipeType(PhoenixRecipeTypes.PLEASE) // Agora isso não será mais nulo
                    .recipeModifiers(GTRecipeModifiers.PARALLEL_HATCH, PhoenixRecipeModifiers.HEAT_DRAWN,
                            GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK_SUBTICK))
                    .pattern(definition -> FactoryBlockPattern.start()
                            .aisle("BBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB", "BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB",
                                    "ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA", "AABBBAAAAAAAAAAACAAAAAAAAAAABBBAA",
                                    "AAABBBAAAAAAAAACCCAAAAAAAAABBBAAA", "AAAABBBAAAAAAACCDCCAAAAAAABBBAAAA",
                                    "AAAAABBBAAAAACCEDECCAAAAABBBAAAAA", "AAAAAABBBAAACCFEDEFCCAAABBBAAAAAA",
                                    "AAAAAAABBBACCFGEHEGFCCABBBAAAAAAA", "AAAAAAAABBBCFIIEHEIIFCBBBAAAAAAAA",
                                    "AAAAAAAAABBBFIIEHEIIFBBBAAAAAAAAA", "AAAAAAAACCBBBFGEHEGFBBBCCAAAAAAAA",
                                    "AAAAAAACCFFBBBFEGEFBBBFFCCAAAAAAA", "AAAAAACCFIIFBBBEGEBBBFIIFCCAAAAAA",
                                    "AAAAACCFGIIGFBBBGBBBFGIIGFCCAAAAA", "AAAACCEEEEEEEEBBBBBEEEEEEEECCAAAA",
                                    "AAACCDDDHHHHGGGBBBGGGHHHHDDDCCAAA", "AAAACCEEEEEEEEBBBBBEEEEEEEECCAAAA",
                                    "AAAAACCFGIIGFBBBGBBBFGIIGFCCAAAAA", "AAAAAACCFIIFBBBEGEBBBFIIFCCAAAAAA",
                                    "AAAAAAACCFFBBBFEGEFBBBFFCCAAAAAAA", "AAAAAAAACCBBBFGEHEGFBBBCCAAAAAAAA",
                                    "AAAAAAAAABBBFIIEHEIIFBBBAAAAAAAAA", "AAAAAAAABBBCFIIEHEIIFCBBBAAAAAAAA",
                                    "AAAAAAABBBACCFGEHEGFCCABBBAAAAAAA", "AAAAAABBBAAACCFEDEFCCAAABBBAAAAAA",
                                    "AAAAABBBAAAAACCEDECCAAAAABBBAAAAA", "AAAABBBAAAAAAACCDCCAAAAAAABBBAAAA",
                                    "AAABBBAAAAAAAAACCCAAAAAAAAABBBAAA", "AABBBAAAAAAAAAAACAAAAAAAAAAABBBAA",
                                    "ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA", "BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB",
                                    "BBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB")
                            .aisle("BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAJJGGGGGJJAAAAAAAAAAAA", "AAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB")
                            .aisle("ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAJJAAAAAAAJJAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA")
                            .aisle("AABBBAAAAAAAAAAAAAAAAAAAAAAABBBAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "CAAAAAAAAAJJAAAAAAAAAJJAAAAAAAAAC", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AABBBAAAAAAAAAAAAAAAAAAAAAAABBBAA")
                            .aisle("AAABBBAAAAAAAAAAAAAAAAAAAAABBBAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAJJAAAAAAAAAAAJJAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAABBBAAAAAAAAAAAAAAAAAAAAABBBAAA")
                            .aisle("AAAABBBAAAAAAAAAAAAAAAAAAABBBAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "DAAAAAAAJJAAAAAAAAAAAAAJJAAAAAAAD", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAABBBAAAAAAAAAAAAAAAAAAABBBAAAA")
                            .aisle("AAAAABBBAAAAAAAACAAAAAAAABBBAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "DAAAAAAJJAAAAAAJJJAAAAAAJJAAAAAAD", "EAAAAAAAAAAAAJJJJJJJAAAAAAAAAAAAE",
                                    "CAAAAAAAAAAAAAAJJJAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAABBBAAAAAAAACAAAAAAAABBBAAAAA")
                            .aisle("AAAAAABBBAAAAAACCCAAAAAABBBAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "FAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAF", "EAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAE",
                                    "DAAAAAJJEAAAJJJJJJJJJAAAEJJAAAAAD", "EAAAAAAEEAAJJJJJJJJJJJAAEEAAAAAAE",
                                    "FAAAAAAEEAAAJJJJJJJJJAAAEEAAAAAAF", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAABBBAAAAAACCCAAAAAABBBAAAAAA")
                            .aisle("AAAAAAABBBAAAACCDCCAAAABBBAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "FAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAF",
                                    "GAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAG", "EAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAE",
                                    "HAAAAJJEEAJJJJJJJJJJJJJAEEJJAAAAH", "EAAAAAAEEAJJJJJJJJJJJJJAEEAAAAAAE",
                                    "GAAAAAAEEAJJJJJJJJJJJJJAEEAAAAAAG", "FAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAF",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAABBBAAAACCGCCAAAABBBAAAAAAA")
                            .aisle("AAAAAAAABBBAACCEDECCAABBBAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAB", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "HAAAJJAAAJJJJAAAAAAAJJJJAAAJJAAAH", "EAAAAAAAAJJJJJAAKAAJJJJJAAAAAAAAE",
                                    "IAAAAAAAAJJJJAAAAAAAJJJJAAAAAAAAI", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "BAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAABBBAACCEGECCAABBBAAAAAAAA")
                            .aisle("AAAAAAAAABBBCCEEHEECCBBBAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "AAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "HAAJJAAAJJJAAAAAKAAAAAJJJAAAJJAAH", "EAAAAAAAJJJJAAAKKKAAAJJJJAAAAAAAE",
                                    "IAAAAAAAJJJAAAAAKAAAAAJJJAAAAAAAI", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAA", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAABBBCCEEHEECCBBBAAAAAAAAA")
                            .aisle("AAAAAAAAAABBBDDHHHDDBBBAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", "EAAAAAAAAAAAAAALLLAAAAAAAAAAAAAAE",
                                    "HAJJAAAAJJAAAALLLLLAAAAJJAAAAJJAH", "EAAAAAAJJJJAAALLLLLAAAJJJJAAAAAAE",
                                    "GAAAAAAAJJAAAALLLLLAAAAJJAAAAAAAG", "FAAAAAAAAAAAAAALLLAAAAAAAAAAAAAAF",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAABBBGGHHHGGBBBAAAAAAAAAA")
                            .aisle("AAAAAAAAAACBBBEEHEEBBBCAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAB",
                                    "FAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAF", "EAAAAAAAAAAAALLAAALLAAAAAAAAAAAAE",
                                    "GJJAAAAJJJAAALAMMMALAAAJJJAAAAJJG", "EAAAAAAJJJAAALAMMMALAAAJJJAAAAAAE",
                                    "FAAAAAAJJJAAALAMMMALAAAJJJAAAAAAF", "BAAAAAAAAAAAALLAAALLAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAACBBBEEHEEBBBCAAAAAAAAAA")
                            .aisle("AAAAAAAAACCDBBBEGEBBBDCCAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAEEAAAEEAAAAAAAAAAAAA", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "CAAAAAAAAAAAAKAAAAAKAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "BAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAKLNAAANLKAAAAAAAAAAAB", "EGAAAAAAAAAALKAAAAAKLAAAAAAAAAAGE",
                                    "GJAAAAAJJAAALKAAAAAKLAAAJJAAAAAJG", "EGAAAAJJJJAALKAAKAAKLAAJJJJAAAAGE",
                                    "BAAAAAAJJAAALKAAAAAKLAAAJJAAAAAAB", "BAAAAAAAAAAALKAAAAAKLAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAKLNAAANLKAAAAAAAAAAAB", "FAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAF",
                                    "IAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAI", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAC", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAEEAAAEEAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAACCGBBBEGEBBBGCCAAAAAAAAA")
                            .aisle("AAAAAAAACCEDEBBBGBBBEDECCAAAAAAAA", "AAAAAAAAAAAAAACCCCCAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAEEAEEAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAEEAAAEEAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAC", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "GAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAG",
                                    "FAAAAAAAAAAAAAKLLLKAAAAAAAAAAAAAF", "BAAAAAAAAAAAKLLAAALLKAAAAAAAAAAAB",
                                    "BAAAAAAAAAAALNKAAAKNLAAAAAAAAAAAB", "BGAAAAAAAAAALAAAAAAALAAAAAAAAAAGB",
                                    "GGAAAAAJJAALAAAAAAAAALAAJJAAAAAGG", "BGAAAAJJJAALAAAAKAAAALAAJJJAAAAGB",
                                    "BAAAAAAJJAALAAAAAAAAALAAJJAAAAAAB", "BAAAAAAAAAAALAAAAAAALAAAAAAAAAAAB",
                                    "FAAAAAAAAAAALNKAAAKNLAAAAAAAAAAAF", "GAAAAAAAAAAAALLAAALLAAAAAAAAAAAAG",
                                    "IAAAAAAAAAAAAKKLLLKKAAAAAAAAAAAAI", "IAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAI",
                                    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "CAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAEEKKKEEAAAAAAAAAAAAA", "AAAAAAAAAAAAAAEEAEEAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAACCCCCAAAAAAAAAAAAAA",
                                    "AAAAAAAACCEGEBBBGBBBEGECCAAAAAAAA")
                            .aisle("AAAAAAACCEEHEEBBBBBEEHEECCAAAAAAA", "AAAAAAAAAAAAAACGGGCAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAEEEAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAEEKEEAAAAAAAAAAAAAA",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "EAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAAOOOAAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAKGGGKAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAE", "EAAAAAAAAAAAALAMMMALAAAAAAAAAAAAE",
                                    "BAAAAAAAAAAALAAAAAAALAAAAAAAAAAAB", "BGAAAAAAAAALAAAAPAAAALAAAAAAAAAGB",
                                    "BGAAAAJJJAALMAAPAPAAMLAAJJJAAAAGB", "BGAAAAJJJAKLMAAAKAAAMLKAJJJAAAAGB",
                                    "BAAAAAJJJAALMAAPAPAAMLAAJJJAAAAAB", "EAAAAAAAAAALAAAAPAAAALAAAAAAAAAAE",
                                    "EAAAAAAAAAAALAAAAAAALAAAAAAAAAAAE", "EAAAAAAAAAAAALAMMMALAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAALLLLLAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAKGGGKAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAE", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAC", "AAAAAAAAAAAAAAEEKEEAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAEEEAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAACGGGCAAAAAAAAAAAAAA",
                                    "AAAAAAACCEEHEEBBBBBEEHEECCAAAAAAA")
                            .aisle("AAAAAACCDDHHHGGBBBGGHHHDDCCAAAAAA", "AAAAAAAAAAAAAACGGGCAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAEEEAAAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAKQKAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAC", "DAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAD",
                                    "DAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAD", "DAAAAAAAAAAAAAAOOOAAAAAAAAAAAAAAD",
                                    "HAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAH", "HAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAH",
                                    "HAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAH", "HAAAAAAAAAAAAAAGQGAAAAAAAAAAAAAAH",
                                    "GAAAAAAAAAAAAALLLLLAAAAAAAAAAAAAG", "GAAAAAAAAAAAALAMMMALAAAAAAAAAAAAG",
                                    "GAAAAAAAAAAALAAAKAAALAAAAAAAAAAAG", "BGAAAAAGAAALAAAPKPAAALAAAAAAAAAGB",
                                    "BGAAAAJJJAKLMAAAKAAAMLKAJJJAAAAGB", "BGAAAAJJJKKLMKKKRKKKMLKKJJJAAAAGB",
                                    "GAAAAAJJJAKLMAAAKAAAMLKAJJJAAAAAG", "GAAAAAAAAAALAAAPKPAAALAAAAAAAAAAG",
                                    "GAAAAAAAAAAALAAAKAAALAAAAAAAAAAAG", "HAAAAAAAAAAAALAMMMALAAAAAAAAAAAAH",
                                    "HAAAAAAAAAAAAALLLLLAAAAAAAAAAAAAH", "HAAAAAAAAAAAAAAGQGAAAAAAAAAAAAAAH",
                                    "HAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAH", "DAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAD",
                                    "DAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAD", "DAAAAAAAAAAAAAKAKAKAAAAAAAAAAAAAD",
                                    "CAAAAAAAAAAAAAKAKAKAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAKQKAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAAAEEEAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAACGGGCAAAAAAAAAAAAAA",
                                    "AAAAAACCGGHHHGGBBBGGHHHGGCCAAAAAA")
                            .aisle("AAAAAAACCEEHEEBBBBBEEHEECCAAAAAAA", "AAAAAAAAAAAAAACGGGCAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAEEEAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAEEKEEAAAAAAAAAAAAAA",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "EAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAAOOOAAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAKKKAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAKGGGKAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAE", "EAAAAAAAAAAAALAMMMALAAAAAAAAAAAAE",
                                    "BAAAAAAAAAAALAAAAAAALAAAAAAAAAAAB", "BGAAAAAAAAALAAAAPAAAALAAAAAAAAAGB",
                                    "BGAAAAJJJAALMAAPAPAAMLAAJJJAAAAGB", "BGAAAAJJJAKLMAAAKAAAMLKAJJJAAAAGB",
                                    "BAAAAAJJJAALMAAPAPAAMLAAJJJAAAAAB", "EAAAAAAAAAALAAAAPAAAALAAAAAAAAAAE",
                                    "EAAAAAAAAAAALAAAAAAALAAAAAAAAAAAE", "EAAAAAAAAAAAALAMMMALAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAALLLLLAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAKGGGKAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "EAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAE", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAKAKAKAAAAAAAAAAAAAC", "AAAAAAAAAAAAAAEEKEEAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAEEEAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAACGGGCAAAAAAAAAAAAAA",
                                    "AAAAAAACCEEHEEBBBBBEEHEECCAAAAAAA")
                            .aisle("AAAAAAAACCEDEBBBGBBBEDECCAAAAAAAA", "AAAAAAAAAAAAAACCCCCAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAEEAEEAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAEEAAAEEAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAC", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "GAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAG",
                                    "FAAAAAAAAAAAAAKLLLKAAAAAAAAAAAAAF", "BAAAAAAAAAAAKLLAAALLKAAAAAAAAAAAB",
                                    "BAAAAAAAAAAALNKAAAKNLAAAAAAAAAAAB", "BGAAAAAAAAAALAAAAAAALAAAAAAAAAAGB",
                                    "GGAAAAAJJAALAAAAAAAAALAAJJAAAAAGG", "BGAAAAJJJAALAAAAKAAAALAAJJJAAAAGB",
                                    "BAAAAAAJJAALAAAAAAAAALAAJJAAAAAAB", "BAAAAAAAAAAALAAAAAAALAAAAAAAAAAAB",
                                    "FAAAAAAAAAAALNKAAAKNLAAAAAAAAAAAF", "GAAAAAAAAAAAALLAAALLAAAAAAAAAAAAG",
                                    "IAAAAAAAAAAAAKKLLLKKAAAAAAAAAAAAI", "IAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAI",
                                    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "CAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAEEKKKEEAAAAAAAAAAAAA", "AAAAAAAAAAAAAAEEAEEAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAACCCCCAAAAAAAAAAAAAA",
                                    "AAAAAAAACCEGEBBBGBBBEGECCAAAAAAAA")
                            .aisle("AAAAAAAAACCDBBBEGEBBBDCCAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAEEAAAEEAAAAAAAAAAAAA", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "CAAAAAAAAAAAAKAAAAAKAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "BAAAAAAAAAAAAAAKAKAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAKLNAAANLKAAAAAAAAAAAB", "EGAAAAAAAAAALKAAAAAKLAAAAAAAAAAGE",
                                    "GJAAAAAJJAAALKAAAAAKLAAAJJAAAAAJG", "EGAAAAJJJJAALKAAKAAKLAAJJJJAAAAGE",
                                    "BAAAAAAJJAAALKAAAAAKLAAAJJAAAAAAB", "BAAAAAAAAAAALKAAAAAKLAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAKLNAAANLKAAAAAAAAAAAB", "FAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAF",
                                    "IAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAI", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAC", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAEEAAAEEAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAACCGBBBEGEBBBGCCAAAAAAAAA")
                            .aisle("AAAAAAAAAACBBBEEHEEBBBCAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAKAAAKAAAAAAAAAAAAAB",
                                    "FAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAF", "EAAAAAAAAAAAALLAAALLAAAAAAAAAAAAE",
                                    "GJJAAAAJJJAAALAMMMALAAAJJJAAAAJJG", "EAAAAAAJJJAAALAMMMALAAAJJJAAAAAAE",
                                    "FAAAAAAJJJAAALAMMMALAAAJJJAAAAAAF", "BAAAAAAAAAAAALLAAALLAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAKLLLLLKAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "AAAAAAAAAAAAEEAAAAAEEAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAACBBBEEHEEBBBCAAAAAAAAAA")
                            .aisle("AAAAAAAAAABBBDDHHHDDBBBAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF",
                                    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG", "EAAAAAAAAAAAAAALLLAAAAAAAAAAAAAAE",
                                    "HAJJAAAAJJAAAALLLLLAAAAJJAAAAJJAH", "EAAAAAAJJJJAAALLLLLAAAJJJJAAAAAAE",
                                    "GAAAAAAAJJAAAALLLLLAAAAJJAAAAAAAG", "FAAAAAAAAAAAAAALLLAAAAAAAAAAAAAAF",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "AAAAAAAAAAAEEAAAAAAAEEAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAABBBGGHHHGGBBBAAAAAAAAAA")
                            .aisle("AAAAAAAAABBBCCEEHEECCBBBAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "AAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "HAAJJAAAJJJAAAAAKAAAAAJJJAAAJJAAH", "EAAAAAAAJJJJAAAKKKAAAJJJJAAAAAAAE",
                                    "IAAAAAAAJJJAAAAAKAAAAAJJJAAAAAAAI", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAA", "AAAAAAAAAAEEAAAAAAAAAEEAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAABBBCCEEHEECCBBBAAAAAAAAA")
                            .aisle("AAAAAAAABBBAACCEDECCAABBBAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAB", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "HAAAJJAAAJJJJAAAAAAAJJJJAAAJJAAAH", "EAAAAAAAAJJJJJAAKAAJJJJJAAAAAAAAE",
                                    "IAAAAAAAAJJJJAAAAAAAJJJJAAAAAAAAI", "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI",
                                    "FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "BAAAAAAAAEEAAAAAAAAAAAEEAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAABBBAACCEGECCAABBBAAAAAAAA")
                            .aisle("AAAAAAABBBAAAACCDCCAAAABBBAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "FAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAF",
                                    "GAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAG", "EAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAE",
                                    "HAAAAJJEEAJJJJJJJJJJJJJAEJJJAAAAH", "EAAAAAAEEAJJJJJJJJJJJJJAEEAAAAAAE",
                                    "GAAAAAAEEAJJJJJJJJJJJJJAEEAAAAAAG", "FAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAF",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "BAAAAAAAEEAAAAAAAAAAAAAEEAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAABBBAAAACCGCCAAAABBBAAAAAAA")
                            .aisle("AAAAAABBBAAAAAACCCAAAAAABBBAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "FAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAF", "EAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAE",
                                    "DAAAAAJJEAAAJJJJJJJJJAAAJJJAAAAAD", "EAAAAAAEEAAJJJJJJJJJJJAAEEAAAAAAE",
                                    "FAAAAAAEEAAAJJJJJJJJJAAAEEAAAAAAF", "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC",
                                    "CAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAC", "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA",
                                    "AAAAAAAEEAAAAAAAAAAAAAAAEEAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAABBBAAAAAACCCAAAAAABBBAAAAAA")
                            .aisle("AAAAABBBAAAAAAAACAAAAAAAABBBAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE",
                                    "DAAAAAAJJAAAAAAJJJAAAAAAJJAAAAAAD", "EAAAAAAAAAAAAJJJJJJJAAAAAAAAAAAAE",
                                    "CAAAAAAAAAAAAAAJJJAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAABBBAAAAAAAACAAAAAAAABBBAAAAA")
                            .aisle("AAAABBBAAAAAAAAAAAAAAAAAAABBBAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "DAAAAAAAJJAAAAAAAAAAAAAJJAAAAAAAD", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAABBBAAAAAAAAAAAAAAAAAAABBBAAAA")
                            .aisle("AAABBBAAAAAAAAAAAAAAAAAAAAABBBAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "CAAAAAAAAJJAAAAAAAAAAAJJAAAAAAAAC", "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAABBBAAAAAAAAAAAAAAAAAAAAABBBAAA")
                            .aisle("AABBBAAAAAAAAAAAAAAAAAAAAAAABBBAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "CAAAAAAAAAJJAAAAAAAAAJJAAAAAAAAAC", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AABBBAAAAAAAAAAAAAAAAAAAAAAABBBAA")
                            .aisle("ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAJJAAAAAAAJJAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA")
                            .aisle("BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAJJGGGGGJJAAAAAAAAAAAA", "AAAAAAAAAAAAAGGGGGGGAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                                    "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB", "BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB",
                                    "BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB")
                            .aisle("BBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB", "BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB",
                                    "ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA", "AABBBAAAAAAAAAAACAAAAAAAAAAABBBAA",
                                    "AAABBBAAAAAAAAACCCAAAAAAAAABBBAAA", "AAAABBBAAAAAAACCDCCAAAAAAABBBAAAA",
                                    "AAAAABBBAAAAACCEDECCAAAAABBBAAAAA", "AAAAAABBBAAACCFEDEFCCAAABBBAAAAAA",
                                    "AAAAAAABBBACCFGEHEGFCCABBBAAAAAAA", "AAAAAAAABBBCFIIEHEIIFCBBBAAAAAAAA",
                                    "AAAAAAAAABBBFIIEHEIIFBBBAAAAAAAAA", "AAAAAAAACCBBBFGEHEGFBBBCCAAAAAAAA",
                                    "AAAAAAACCFFBBBFEGEFBBBFFCCAAAAAAA", "AAAAAACCFIIFBBBEGEBBBFIIFCCAAAAAA",
                                    "AAAAACCFGIIGFBBBGBBBFGIIGFCCAAAAA", "AAAACCEEEEEEEEBBBBBEEEEEEEECCAAAA",
                                    "AAACCDDDHHHHGGGBSBGGGHHHHDDDCCAAA", "AAAACCEEEEEEEEBBBBBEEEEEEEECCAAAA",
                                    "AAAAACCFGIIGFBBBGBBBFGIIGFCCAAAAA", "AAAAAACCFIIFBBBEGEBBBFIIFCCAAAAAA",
                                    "AAAAAAACCFFBBBFEGEFBBBFFCCAAAAAAA", "AAAAAAAACCBBBFGEHEGFBBBCCAAAAAAAA",
                                    "AAAAAAAAABBBFIIEHEIIFBBBAAAAAAAAA", "AAAAAAAABBBCFIIEHEIIFCBBBAAAAAAAA",
                                    "AAAAAAABBBACCFGEHEGFCCABBBAAAAAAA", "AAAAAABBBAAACCFEDEFCCAAABBBAAAAAA",
                                    "AAAAABBBAAAAACCEDECCAAAAABBBAAAAA", "AAAABBBAAAAAAACCDCCAAAAAAABBBAAAA",
                                    "AAABBBAAAAAAAAACCCAAAAAAAAABBBAAA", "AABBBAAAAAAAAAAACAAAAAAAAAAABBBAA",
                                    "ABBBAAAAAAAAAAAAAAAAAAAAAAAAABBBA", "BBBAAAAAAAAAAAAAAAAAAAAAAAAAAABBB",
                                    "BBAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB")
                            .where('A', any())
                            .where('B',
                                    blocks(PhoenixBlocks.PHOENIX_ENRICHED_TRITANIUM_CASING.get())
                                            .setMinGlobalLimited(575).setPreviewCount(1200)
                                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
                                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)
                                                    .setMinGlobalLimited(1))
                                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
                                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
                                            .or(autoAbilities(true, false, true)))
                            .where('C',
                                    blocks(ChemicalHelper.getBlock(TagPrefix.frameGt,
                                            PhoenixMaterials.PHOENIX_ENRICHED_TRITANIUM)))
                            .where('D', blocks(ADVANCED_COMPUTER_CASING.get()))
                            .where('E', blocks(ChemicalHelper.getBlock(TagPrefix.frameGt, GTMaterials.Neutronium)))
                            .where('F', blocks(COMPUTER_CASING.get()))
                            .where('G', blocks(PhoenixBlocks.COIL_TRUE_HEAT_STABLE.get()))
                            .where('H', blocks(PhoenixBlocks.STABLE_LOGIC_CASING.get()))
                            .where('I', blocks(GTResearchMachines.HPCA_BRIDGE_COMPONENT.get()))
                            .where('J', blocks(PhoenixBlocks.RELIABLE_NAQUADAH_ALLOY_MACHINE_CASING.get()))
                            .where('K',
                                    blocks(ChemicalHelper.getBlock(TagPrefix.frameGt,
                                            PhoenixMaterials.PHOENIX_ENRICHED_NAQUADAH)))
                            .where('L', blocks(PhoenixBlocks.SUPER_STABLE_FUSION_CASING.get())
                                    .or(blocks(ForgeRegistries.BLOCKS
                                            .getValue(new ResourceLocation("kubejs", "phoenix_gaze_panel")))))
                            .where('M', blocks(PhoenixBlocks.BLAZING_CORE_STABILIZER.get()))
                            .where("N",
                                    blocks(ForgeRegistries.BLOCKS.getValue(
                                            new ResourceLocation("draconicevolution", "awakened_draconium_block"))))
                            .where("O",
                                    blocks(ForgeRegistries.BLOCKS
                                            .getValue(new ResourceLocation("expatternprovider", "fishbig"))))
                            .where('P', blocks(PhoenixBlocks.GLITCHED_ENTROPY_CASING.get()))
                            .where("Q",
                                    blocks(ForgeRegistries.BLOCKS
                                            .getValue(new ResourceLocation("ae2", "creative_energy_cell"))))
                            .where('R', blocks(PhoenixBlocks.PHOENIX_HEART_CASING.get()))
                            .where('S', controller(blocks(definition.getBlock())))
                            .build())
                    .model(
                            createWorkableCasingMachineModel(
                                    phoenixcore.id("block/phoenix_enriched_tritanium_casing"),
                                    GTCEu.id("block/multiblock/fusion_reactor"))
                                    .andThen(d -> d
                                            .addDynamicRenderer(
                                                    CosmicDynamicRenderHelpers::getPlasmaArcFurnaceRenderer)))
                    .hasBER(true)
                    .register();
        }
    }
    Component myColoredText = Component.translatable("block.phoenixcore.high_yield_photon_emission_regulator")
            .withStyle(style -> style.withColor(TextColor.fromRgb(0xFF00FF)));

    static {
        if (PhoenixConfigs.INSTANCE.features.PHPCAEnabled) {
            // 2. Mova toda a lógica de registro para dentro do método init()
            HIGH_YEILD_PHOTON_EMISSION_REGULATER = REGISTRATE
                    .multiblock("high_yield_photon_emission_regulator", PhoenixHPCAMachine::new)
                    .langValue("block.phoenixcore.high_yield_photon_emission_regulator")
                    .tooltips(Component.translatable("phoenixcore.tooltip.hyper_machine_purpose",
                            GTMaterials.get(INSTANCE.features.ActiveCoolerCoolantBase).getLocalizedName()
                                    .withStyle(style -> style.withColor(TextColor.fromRgb(GTMaterials
                                            .get(INSTANCE.features.ActiveCoolerCoolantBase).getMaterialARGB()))),
                            GTMaterials.get(INSTANCE.features.ActiveCoolerCoolant1).getLocalizedName()
                                    .withStyle(style -> style.withColor(TextColor.fromRgb(GTMaterials
                                            .get(INSTANCE.features.ActiveCoolerCoolant1).getMaterialARGB()))),
                            GTMaterials.get(INSTANCE.features.ActiveCoolerCoolant2).getLocalizedName()
                                    .withStyle(style -> style.withColor(TextColor.fromRgb(GTMaterials
                                            .get(INSTANCE.features.ActiveCoolerCoolant2).getMaterialARGB())))),
                            Component.translatable("phoenixcore.tooltip.hyper_machine_1"),
                            Component
                                    .translatable("phoenixcore.tooltip.hyper_machine_coolant_base",
                                            GTMaterials.get(INSTANCE.features.ActiveCoolerCoolantBase)
                                                    .getLocalizedName(),
                                            INSTANCE.features.BaseCoolantBoost)
                                    .withStyle(style -> style.withColor(TextColor.fromRgb(GTMaterials
                                            .get(INSTANCE.features.ActiveCoolerCoolantBase).getMaterialARGB()))),
                            Component.translatable("phoenixcore.tooltip.hyper_machine_coolant2",
                                    GTMaterials.get(INSTANCE.features.ActiveCoolerCoolant1).getLocalizedName(),
                                    INSTANCE.features.CoolantBoost1)
                                    .withStyle(style -> style.withColor(TextColor.fromRgb(GTMaterials
                                            .get(INSTANCE.features.ActiveCoolerCoolant1).getMaterialARGB()))),
                            Component
                                    .translatable("phoenixcore.tooltip.hyper_machine_coolant3",
                                            GTMaterials.get(INSTANCE.features.ActiveCoolerCoolant2).getLocalizedName(),
                                            INSTANCE.features.CoolantBoost2)
                                    .withStyle(style -> style.withColor(TextColor.fromRgb(GTMaterials
                                            .get(INSTANCE.features.ActiveCoolerCoolant2).getMaterialARGB()))))
                    .rotationState(RotationState.NON_Y_AXIS)
                    .appearanceBlock(ADVANCED_COMPUTER_CASING)
                    .recipeType(GTRecipeTypes.DUMMY_RECIPES)
                    .tooltips(LangHandler.getMultiLang("gtceu.machine.high_performance_computation_array.tooltip"))
                    .pattern(definition -> FactoryBlockPattern.start()
                            .aisle("BBBBCCCBBBB", "CDDCCCCCDDC", "CCDCCCCCDCC", "CCCCCCCCCCC", "CCCCCCCCCCC",
                                    "CCCCCCCCCCC", "CCCCCCCCCCC", "CCCCCCCCCCC", "CCCCCCCCCCC", "CCCCCCCCCCC")
                            .aisle("BEEBBBBBEEB", "DEEEFFFEEED", "DEEFGGGFEED", "DDDFGGGFDDD", "CBBFGGGFBBC",
                                    "CBBFGGGFBBC", "CCBFGGGFBCC", "CCBEFFFEBCC", "CCBBBBBBBCC", "CCBBBBBBBCC")
                            .aisle("BBHHIIIHHBB", "CDDAAAAADDC", "CIDAAAAADIC", "CIAAAAAAAIC", "CIAAAAAAAIC",
                                    "CEAAAAAAAEC", "CEAAAAAAAEC", "CEAAAAAAAEC", "CEAAAAAAAEC", "CBBIIIIIBBC")
                            .aisle("CBIIIIIIIBC", "CJAAAKAAAJC", "CJAAAKAAAJC", "CJAAAKAAAJC", "CFAAAKAAAFC",
                                    "CLAAAKAAALC", "CLAAAKAAALC", "CLAAAKAAALC", "CFAAAAAAAFC", "CBIIIIIIIBC")
                            .aisle("CBIIIIIIIBC", "CJAAKMKAAJC", "CJAAKMKAAJC", "CJAAKMKAAJC", "CFAAKMKAAFC",
                                    "CLAAKMKAALC", "CLAAKMKAALC", "CLAAKMKAALC", "CFAAAAAAAFC", "CBIIIIIIIBC")
                            .aisle("CBIIIIIIIBC", "CJAAAKAAAJC", "CJAAAKAAAJC", "CJAAAKAAAJC", "CFAAAKAAAFC",
                                    "CLAAAKAAALC", "CLAAAKAAALC", "CLAAAKAAALC", "CFAAAAAAAFC", "CBIIIIIIIBC")
                            .aisle("BBHHIIIHHBB", "CDDAAAAADDC", "CIDAAAAADIC", "CIAAAAAAAIC", "CIAAAAAAAIC",
                                    "CEAAAAAAAEC", "CEAAAAAAAEC", "CEAAAAAAAEC", "CEAAAAAAAEC", "CBBIIIIIBBC")
                            .aisle("BEEBBNBBEEB", "DEEEFFFEEED", "DEEOJJJOEED", "DDDOJJJODDD", "CBBOJJJOBBC",
                                    "CBBOJJJOBBC", "CCBBJJJBBCC", "CCBBJJJBBCC", "CCBBBBBBBCC", "CCBBBBBBBCC")
                            .aisle("BBBBCCCBBBB", "CDDCCCCCDDC", "CCDCCCCCDCC", "CCCCCCCCCCC", "CCCCCCCCCCC",
                                    "CCCCCCCCCCC", "CCCCCCCCCCC", "CCCCCCCCCCC", "CCCCCCCCCCC", "CCCCCCCCCCC")
                            .where("A", air())
                            .where('B', blocks(PhoenixBlocks.SPACE_TIME_COOLED_ETERNITY_CASING.get()))
                            .where('C', any())
                            .where('D', blocks(PhoenixBlocks.AKASHIC_ZERONIUM_CASING.get()))
                            .where('E', blocks(ADVANCED_COMPUTER_CASING.get()).setMinGlobalLimited(20)
                                    .or(abilities(PartAbility.INPUT_ENERGY).setMinGlobalLimited(1)
                                            .setMaxGlobalLimited(2, 1))
                                    .or(abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1))
                                    .or(abilities(PartAbility.COMPUTATION_DATA_TRANSMISSION).setExactLimit(1))
                                    .or(autoAbilities(true, false, false)))
                            .where('F', blocks(COMPUTER_HEAT_VENT.get()))
                            .where('G', blocks(PhoenixResearchMachines.ADVANCED_PHOENIX_COMPUTATION_COMPONENT.get())
                                    .or(blocks(PhoenixResearchMachines.ADVANCED_PHOENIX_COMPUTATION_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_ADVANCED_COMPUTATION_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_EMPTY_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_COMPUTATION_COMPONENT.get())))
                            .where('H', blocks(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING.get()))
                            .where('I', blocks(COMPUTER_CASING.get()))
                            .where('J', blocks(FUSION_GLASS.get()))
                            .where('K', blocks(PhoenixBlocks.AKASHIC_COIL_BLOCK.get()))
                            .where('L', blocks(PhoenixResearchMachines.ACTIVE_PHOENIX_COOLER_COMPONENT.get())
                                    .or(blocks(PhoenixResearchMachines.PHOENIX_COOLER_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_EMPTY_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_BRIDGE_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_ACTIVE_COOLER_COMPONENT.get()))
                                    .or(blocks(GTResearchMachines.HPCA_HEAT_SINK_COMPONENT.get())))
                            .where('M', blocks(PhoenixBlocks.PERFECTED_LOGIC.get()))
                            .where('N', controller(blocks(definition.getBlock())))
                            .where('O', blocks(GCYMBlocks.HEAT_VENT.get()))
                            .build())
                    /*
                     * .shapeInfos(definition -> {
                     * List<MultiblockShapeInfo> shapeInfo = new ArrayList<>();
                     * .ShapeInfoBuilder builder = MultiblockShapeInfo.builder()
                     * .aisle("SA", "CC", "CC", "OC", "AA")
                     * .aisle("VA", "8V", "5V", "2V", "VA")
                     * .aisle("VA", "7V", "4V", "1V", "VA")
                     * .aisle("VA", "6V", "3V", "0V", "VA")
                     * .aisle("AA", "EC", "MC", "HC", "AA")
                     * .where('S', GTResearchMachines.HIGH_PERFORMANCE_COMPUTING_ARRAY, Direction.NORTH)
                     * .where('A', ADVANCED_COMPUTER_CASING)
                     * .where('V', COMPUTER_HEAT_VENT)
                     * .where('C', COMPUTER_CASING)
                     * .where('E', GTMachines.ENERGY_INPUT_HATCH[GTValues.LuV], Direction.SOUTH)
                     * .where('H', GTMachines.FLUID_IMPORT_HATCH[GTValues.LV], Direction.SOUTH)
                     * .where('O', GTResearchMachines.COMPUTATION_HATCH_TRANSMITTER, Direction.NORTH)
                     * .where('M', ConfigHolder.INSTANCE.machines.enableMaintenance ?
                     * GTMachines.MAINTENANCE_HATCH.defaultBlockState().setValue(
                     * GTMachines.MAINTENANCE_HATCH.get().getRotationState().property,
                     * Direction.SOUTH) :
                     * COMPUTER_CASING.getDefaultState());
                     * 
                     * // a few example structures
                     * shapeInfo.add(builder.shallowCopy()
                     * .where('0', GTResearchMachines.HPCA_EMPTY_COMPONENT, Direction.WEST)
                     * .where('1', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('2', GTResearchMachines.HPCA_EMPTY_COMPONENT, Direction.WEST)
                     * .where('3', GTResearchMachines.HPCA_EMPTY_COMPONENT, Direction.WEST)
                     * .where('4', GTResearchMachines.HPCA_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('5', GTResearchMachines.HPCA_EMPTY_COMPONENT, Direction.WEST)
                     * .where('6', GTResearchMachines.HPCA_EMPTY_COMPONENT, Direction.WEST)
                     * .where('7', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('8', GTResearchMachines.HPCA_EMPTY_COMPONENT, Direction.WEST)
                     * .build());
                     * 
                     * shapeInfo.add(builder.shallowCopy()
                     * .where('0', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('1', GTResearchMachines.HPCA_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('2', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('3', GTResearchMachines.HPCA_ACTIVE_COOLER_COMPONENT, Direction.WEST)
                     * .where('4', GTResearchMachines.HPCA_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('5', GTResearchMachines.HPCA_BRIDGE_COMPONENT, Direction.WEST)
                     * .where('6', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('7', GTResearchMachines.HPCA_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('8', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .build());
                     * 
                     * shapeInfo.add(builder.shallowCopy()
                     * .where('0', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('1', GTResearchMachines.HPCA_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('2', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('3', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('4', GTResearchMachines.HPCA_ADVANCED_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('5', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('6', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('7', GTResearchMachines.HPCA_BRIDGE_COMPONENT, Direction.WEST)
                     * .where('8', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .build());
                     * 
                     * shapeInfo.add(builder.shallowCopy()
                     * .where('0', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('1', GTResearchMachines.HPCA_ADVANCED_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('2', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('3', GTResearchMachines.HPCA_ACTIVE_COOLER_COMPONENT, Direction.WEST)
                     * .where('4', GTResearchMachines.HPCA_BRIDGE_COMPONENT, Direction.WEST)
                     * .where('5', GTResearchMachines.HPCA_ACTIVE_COOLER_COMPONENT, Direction.WEST)
                     * .where('6', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .where('7', GTResearchMachines.HPCA_ADVANCED_COMPUTATION_COMPONENT, Direction.WEST)
                     * .where('8', GTResearchMachines.HPCA_HEAT_SINK_COMPONENT, Direction.WEST)
                     * .build());
                     * 
                     * return shapeInfo;
                     * })
                     */
                    .sidedWorkableCasingModel(GTCEu.id("block/casings/hpca/advanced_computer_casing"),
                            GTCEu.id("block/multiblock/hpca"))
                    .register();
        }
    }

    public static void init() {}
}
